### ISSUE TITLE
Test summary does consider results from retries

### ISSUE THREAD

**Issue by bdewater** [Shopify/ci-queue#64] opened 2018-03-19 19:31 UTC
As discussed on Slack: https://shopify.slack.com/archives/C9BPSMUDC/p1521483816000555

When a failing (flaky) test turns green after a retry, the test results always keep failing on retry. The failing tests returned are the one before the retry, so the only way to get a passing build is to retry the entire suite 🔥💰

**Comment by casperisfine** [comment] 2018-03-19 22:47
I don't think I understand what you said.

I inspected your build and the issue is actually much trickier than that. But it's more a fault of our CI than to ci-queue to I'll close this issue and open a new one on our CI system.

**Closed by casperisfine** 2018-03-19 22:47 UTC
